backend: vllm
model: Qwen/Qwen3-ASR-1.7B
base_url: http://localhost:8000/v1
image: vllm/vllm-openai:v0.17.1
extra_deps:
  - vllm[audio]==0.17.1
port: 8000
container_name: vllm-stt-server-qwen3
gpu_memory_utilization: 0.95
max_model_len: 8192
max_num_seqs: 1
